const Role = { ADMIN:"ADMIN", LIDER:"LIDER", ANALISTA:"ANALISTA", TESTADOR:"TESTADOR" };
const Prioridade = { BAIXA:"BAIXA", MEDIA:"MEDIA", ALTA:"ALTA" };
const Resultado = { NAO_EXECUTADO:"NAO_EXECUTADO", SUCESSO:"SUCESSO", FALHA:"FALHA", BLOQUEADO:"BLOQUEADO", CANCELADO:"CANCELADO" };
const Criticidade = { BAIXA:"BAIXA", MEDIA:"MEDIA", ALTA:"ALTA" };
const Situacao = { ABERTO:"ABERTO", EM_CORRECAO:"EM_CORRECAO", CORRIGIDO:"CORRIGIDO", EM_TESTES:"EM_TESTES", CONCLUIDO:"CONCLUIDO", CANCELADO:"CANCELADO" };

module.exports = { Role, Prioridade, Resultado, Criticidade, Situacao };